Support current builds of intellij. Fixes #763
klazuka/intellij-elm pull request #767
Opened 2021-09-01 08:26 UTC by boxed

2021-09-12 10:45 UTC, jigargosar requested changes

2021-09-12 10:45 UTC, jigargosar commented on src/main/resources/META-INF/plugin.xml
> +    <idea-version since-build="191.4212.41" until-build="213.*"/>
```suggestion
    <idea-version since-build="191.4212.41"/>
```

Can we complete remove the until-build attribute?

2021-09-12 12:52 UTC, boxed commented
I'm all for it! I just don't know enough about intellij plug-ins to know if that is valid.

2021-09-20 13:32 UTC, mihkell commented
@klazuka This is blocking an update to intellij. As I understand you got new job, but is there anyone else who could review these things as well?

2021-09-20 14:35 UTC, klazuka commented
Fixed by #772 

Sorry for the delay. I decided to just remove the upper-bound entirely.

2021-09-20 14:35 UTC, closed without merging

2021-09-20 14:41 UTC, klazuka commented
Release published: https://github.com/klazuka/intellij-elm/releases/tag/v4.4.1

I also submitted the update to jetbrains plugin repo. So it should be available in the next day or two.